hero_image: images/banner.png
description: Make a cursed profile artefact that opens with HTML and reveals a weird hidden message
listed: false
pdf: false
title: 'Indieweb Cursed Profile Artefact'
landing: true
steps:
  - title: 'Add the cursed file header'
  - title: 'Add the drawer HTML'
    completion:
      - 'engaged'
  - title: 'Give it terminally bad taste'
    completion:
      - 'internal'
  - title: 'Make it look badly famous'
  - title: 'Make the inside look cursed'
    completion:
      - 'external'
