hero_image: images/banner.png
description: Make one forbidden drawer that opens with HTML and reveals a mildly gross surprise
listed: false
pdf: false
title: 'Indieweb Forbidden Drawer'
landing: true
steps:
  - title: 'Label the forbidden drawer'
  - title: 'Hide something suspicious inside'
    completion:
      - 'engaged'
  - title: 'Change the page colours'
    completion:
      - 'internal'
  - title: 'Make the drawer look wrong'
    completion:
      - 'external'
