hero_image: images/banner.png
description: Make a cursed profile artefact that opens with HTML and reveals a weird hidden message
listed: false
pdf: false
title: 'Indieweb Cursed Profile Artefact'
landing: true
steps:
  - title: 'Add the cursed file header'
  - title: 'Build the warning tab'
    completion:
      - 'engaged'
  - title: 'Give it terminally bad taste'
    completion:
      - 'internal'
  - title: 'Add the hidden panel'
  - title: 'Add the cursed message'
    completion:
      - 'external'
